### ISSUE TITLE
May I choose which part to install

### ISSUE THREAD

**Issue by RobinChen95** [iofu728/zsh.sh#3]
I'm deploying the script on my docker ubuntu image，and some function like fzf，I spent 20min to install using the campus wifi， but I won't use it on the virtual machine. 
maybe I can choose which part to install will be better.

**Comment by iofu728** [comment]
Thx.

1. We have [docker version](https://github.com/iofu728/zsh.sh#docker), you can just use it rather than run script by yourself.
2. fzf is very small. Install fzf is only to set some fzf_key_bindings. And we test our script in all of our support Linux distribution, docker version, and cloud platform. It does not need so many time to build. Can you take more info of your test ENV(OS version, dpkg verison, your docker dockerfile, your test screenshots)? Maybe it's a bug.
3. In the future, we will support more plug-in and it will be optional.

**Comment by iofu728** [comment]
When I test the shell script in low-speed which < 10M, there are sometimes will block in connecting GitHub.
So, I change the script to can support rerun.

When you have this problem again, you can interrupt the script and rerun it.

And I test the shell script in the 100M Internet, there is no problem.

fix in #4 🚜prepare for version 0.1.3

**Comment by RobinChen95** [comment]
Thx, that‘s fine, and I'll put this script on my post soon
